
namespace make
{
	/**
	 * Runs the specified command on the shell, optionally with
	 * the specified environment variables.
	 */
	export async function shell(command: string, envVars?: object)
	{
		return new Promise(resolve =>
		{
			const cmd = command.replace(/[\r\n]/g, "").trim();
			const fullEnvVars = Object.assign({}, process.env, envVars || {});
			const proc = ChildProcess.exec(cmd, { env: fullEnvVars });
			proc.stdout!.pipe(process.stdout);
			proc.stderr!.pipe(process.stderr);
			proc.on("exit", (code: number) =>
			{
				console.log("->", cmd, code);
				resolve();
			});
		});
	}

	/**
	 * Spawns a process with given arguments.
	 */
	export function spawn(exe: string, args: string[]): ReturnOfSpawn
	{
		const process = ChildProcess.spawn(exe, args, {
			stdio: "inherit",
		});
		const promise = new Promise<void>((resolve, reject) => 
		{
			process.on("close", function(code) 
			{ 
				code < 0 ?
				reject("Error detected") :
				resolve();
			});
		});
		return { process, promise };
	}

	/**
	 * Holds proc(ChildProcess) and promise(Promise).
	 * proc is ChildProcess instance generated by spawn function.
	 * promise is a Promise that resolves or rejects when spawned process is closed.
	 */
	export type ReturnOfSpawn = {
    process: ReturnType<typeof ChildProcess.spawn>;
    promise: Promise<void>;
	};
	
	/**
	 * Synchronously runs the specified command on the shell.
	 */
	export function shellSync(command: string): string | Error
	{
		try
		{
			const result = ChildProcess.execSync(command);
			return result.toString("utf8").trim();
		}
		catch (e)
		{
			return e;
		}
	}
}
