
namespace Truth
{
	/**
	 * A mapping interface that relates the names of all events generated by
	 * the system, to the function signature of corresponding handlers.
	 */
	export interface ProgramEventMap
	{
		/**
		 * An event that triggers when a new top-level declaration is added
		 * to a document.
		 */
		"declare": (name: string, document: Document) => void;
		
		/**
		 * An event that triggers when a top-level declaration is removed
		 * from a document.
		 */
		"undeclare": (name: string, document: Document) => void;
		
		/**
		 * An event that triggers when a document is created.
		 */
		"documentCreate": (document: Document) => void;
		
		/**
		 * An event that triggers when a document is deleted.
		 */
		"documentDelete": (document: Document) => void;
		
		/**
		 * An event that triggers when the URI associated with document
		 * is modified (typically via some rename operation).
		 */
		"documentUriChange": (document: Document) => void;
		
		/**
		 * An event that triggers when the set of faults that are
		 * detected within the program have changed.
		 */
		"faultChange": (faultsAdded: Fault[], faultsRemoved: Fault[]) => void;
		
		/**
		 * An event that triggers any time the system has completed
		 * a full verification cycle of a program.
		 */
		"verificationComplete": (program: Program) => void;
	}
}
